name: Ppoflix
title: Ppoflix | Yongwook Lee
description: Later equals never.
tags:
  - blog
  - i4song
  - ai
  - math
  - linear algebra
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: i4song.dev@gmail.com
# See: https://disqus.com/
disqus_username: yongwooklee
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: xvonqjgr
